title: SciNLP
# logo: /assets/img/logo.png
description: The 1st SciNLP workshop at AKBC 2020.
show_downloads: false
owner_url: scinlp@googlegroups.com
github:
  is_user_page: false
  is_project_page: false
google_analytics:
theme: jekyll-theme-minimal
